### PR TITLE
Adding the ability to edit the number of minutes timed per phase and topic.

### PR DESCRIPTION
**Pull request by dennis77pr**
One of the things I've noticed while using Kanbonsai is that some meetings need different amounts of time for the group to get through phases of the meeting and especially the topics.  So I implemented this usecase: 

Usecase:  
As the Host of an individual meeting I can edit the number of minutes the timer allows for each phase and each topic in the meeting.  An edit of the timer will update the current phase and any remaining phase as well as all the topics within the meeting.  If the timer is updated during the topics all the remaining topics will be updated.

Acceptance Criteria:
As the Host of an individual meeting I should have the ability to edit the number of minutes tracked by the timer.
As the Host of an individual meeting, when editing the timer I should be presented with a form to enter the number of minutes to set the timer to.
The system should require a number of minutes to be entered.
The system should require the number of minutes to be between 1 and 99.
The system should allow the Host to cancel the edit timer request.
The system will update all remaining phases and topic timers each time the timer is edited.

Known Issues:
If a new user joins the meeting after the timer has been edited the user will not see the updated timer until the host moves to the next phase.

### CODE REVIEW

**Comment by dennis77pr** [comment]
After sending the pull request I noticed another issue.  Editing the time in one meeting seems to update the time in another meeting. This issue would need to be fixed before the pull request is accepted.  I will have to take a look at how to fix that.

**Comment by dennis77pr** [comment]
Ok, I found the bug in the meetings updating each other's timers.  I will close this pull request and try again.

**Comment by dennis77pr** [comment]
Actually just noticed that the bug fix was added to this pull request so reopened it.

**Comment by Ellisande** [comment]
The other thing I noticed is that when you change the timer it does not send out an event to update it on all the connected clients. This causes the current user to see the change, but no one else in the room does.

**Comment by dennis77pr** [comment]
Yep, thanks for pointing that out.  Last commit should fix that issue.

**Comment by Ellisande** [comment]
You're stuff looks good. Merge it in. I'll get this pulled in to the other version we're running

**Pull request merged**
